[package]
name = "shared_thread"
version = "0.1.0"
authors = ["oconnor663@gmail.com"]
license = "MIT"
repository = "https://github.com/oconnor663/shared_thread.rs"
documentation = "https://docs.rs/shared_thread"
readme = "README.md"
description = "similar to shared_child, but for threads instead of processes"
edition = "2021"
